name: cicd pipeline for terraform and ansible
on:
    push:
        branches:
            - main
jobs:
    terraform:
        name: Terraform deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout config files
              uses: actions/checkout@v2

            - name: Setup terraform 
              uses: hashicorp/setup-terraform@v3.1.2

            - name: "Configure AWS Credentials" 
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1         
            
            - name: Setup ssh keys
              run: |
                mkdir ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
                chmod 600 ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa.pub
                ls -la ~/.ssh
              
            - name: Terraform init
              run: terraform init
              working-directory: ./terraform

            - name: Terraform apply
              run: terraform apply -auto-approve
              working-directory: ./terraform

    ansible:
        name: Ansible deployments
        needs: terraform
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install ansible
              run: sudo apt update && sudo apt install ansible -y

            - name: Install ansible galaxy roles
              run: ansible-galaxy install -r ./ansible/requirements.yml

            - name: Install prom
              run: ansible-playbook -i ./ansible/inventory.ini ./ansible/promethus.yml

            - name: Install grafana
              run: ansible-playbook -i ./ansible/inventory.ini ./ansible/grafana.yml
              